version: '2'
services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:1.3.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
  peer0.hq.example.com:
    container_name: peer0.hq.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hq.example.com
      - CORE_PEER_ADDRESS=peer0.hq.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hq.example.com:7051
      - CORE_PEER_LOCALMSPID=HqMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/hq.example.com/peers/peer0.hq.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/hq.example.com/peers/peer0.hq.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.hq.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
  peer0.branch1.example.com:
    container_name: peer0.branch1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.branch1.example.com
      - CORE_PEER_ADDRESS=peer0.branch1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.branch1.example.com:7051
      - CORE_PEER_LOCALMSPID=Branch1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/branch1.example.com/peers/peer0.branch1.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/branch1.example.com/peers/peer0.branch1.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.branch1.example.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
  peer0.branch2.example.com:
    container_name: peer0.branch2.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.branch2.example.com
      - CORE_PEER_ADDRESS=peer0.branch2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.branch2.example.com:7051
      - CORE_PEER_LOCALMSPID=Branch2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/branch2.example.com/peers/peer0.branch2.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/branch2.example.com/peers/peer0.branch2.example.com/tls:/etc/hyperledger/fabric/tls
      - peer0.branch2.example.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
