Organizations:
  - &ref_5
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: OR('OrdererMSP.member')
      Writers:
        Type: Signature
        Rule: OR('OrdererMSP.member')
      Admins:
        Type: Signature
        Rule: OR('OrdererMSP.admin')
  - &ref_7
    Name: HqMSP
    ID: HqMSP
    MSPDir: crypto-config/peerOrganizations/hq.mtct.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: 'OR(''HqMSP.admin'', ''HqMSP.peer'', ''HqMSP.client'')'
      Writers:
        Type: Signature
        Rule: 'OR(''HqMSP.admin'', ''HqMSP.client'')'
      Admins:
        Type: Signature
        Rule: OR('HqMSP.admin')
    AnchorPeers:
      - Host: peer0.hq.mtct.com
        Port: 7051
  - &ref_8
    Name: Branch1MSP
    ID: Branch1MSP
    MSPDir: crypto-config/peerOrganizations/branch1.mtct.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: 'OR(''Branch1MSP.admin'', ''Branch1MSP.peer'', ''Branch1MSP.client'')'
      Writers:
        Type: Signature
        Rule: 'OR(''Branch1MSP.admin'', ''Branch1MSP.client'')'
      Admins:
        Type: Signature
        Rule: OR('Branch1MSP.admin')
    AnchorPeers:
      - Host: peer0.branch1.mtct.com
        Port: 7051
  - &ref_9
    Name: Branch2MSP
    ID: Branch2MSP
    MSPDir: crypto-config/peerOrganizations/branch2.mtct.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: 'OR(''Branch2MSP.admin'', ''Branch2MSP.peer'', ''Branch2MSP.client'')'
      Writers:
        Type: Signature
        Rule: 'OR(''Branch2MSP.admin'', ''Branch2MSP.client'')'
      Admins:
        Type: Signature
        Rule: OR('Branch2MSP.admin')
    AnchorPeers:
      - Host: peer0.branch2.mtct.com
        Port: 7051
Capabilities:
  Channel:
    V1_3: true
  Orderer:
    V1_1: true
  Application:
    V1_3: true
    V1_2: false
    V1_1: false
Application:
  Organizations: null
  Policies: &ref_10
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
Orderer:
  OrdererType: solo
  Addresses: &ref_2
    - 'orderer.example.com:7050'
  BatchTimeout: 2s
  BatchSize: &ref_3
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka: &ref_4
    Brokers:
      - '127.0.0.1:9092'
  Organizations: null
  Policies: &ref_6
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    BlockValidation:
      Type: ImplicitMeta
      Rule: ANY Writers
Channel:
  Policies: &ref_0
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
  Capabilities: &ref_1
    V1_3: true
Profiles:
  TwoOrgsOrdererGenesis:
    Policies: *ref_0
    Capabilities: *ref_1
    Orderer:
      OrdererType: solo
      Addresses: *ref_2
      BatchTimeout: 2s
      BatchSize: *ref_3
      Kafka: *ref_4
      Organizations:
        - *ref_5
      Policies: *ref_6
      Capabilities:
        V1_1: true
    Consortiums:
      SampleConsortium:
        Organizations:
          - *ref_7
          - *ref_8
          - *ref_9
  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
        - *ref_7
        - *ref_8
        - *ref_9
      Policies: *ref_10
      Capabilities:
        V1_3: true
        V1_2: false
        V1_1: false
