OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Hq
    Domain: hq.mtct.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Branch1
    Domain: branch1.mtct.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Branch2
    Domain: branch2.mtct.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
